vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/assets/uploads/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        property_video:
            uri_prefix: /uploads/videos
            upload_destination: '%kernel.project_dir%/public/assets/uploads/videos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


        property_illustration:
            uri_prefix: /uploads/illustrations
            upload_destination: '%kernel.project_dir%/public/assets/uploads/illustrations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        property_voixOff:
            uri_prefix: /uploads/voixOff
            upload_destination: '%kernel.project_dir%/public/assets/uploads/voixOff'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
